name: MuleSoft CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    if: contains(github.ref, 'main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean -DskipTests install

  test:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run MUnit tests
        run: echo ""

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Package Mule application
        run: mvn package

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Deploy to CloudHub
        env:
          CLOUDHUB_USERNAME: ${{ secrets.anypoint_platform_username }}
          CLOUDHUB_PASSWORD: ${{ secrets.anypoint_platform_password }}
        run: mvn deploy -DskipMunitTests -DmuleDeploy \
         -Dmule.artifact=test \
         -Danypoint.username="$CLOUDHUB_USERNAME" \
         -Danypoint.password="$CLOUDHUB_PASSWORD" \
         -Ddecryption.key=12345
